#Copyright 2022 Google LLC.
#SPDX-License-Identifier: Apache-2.0

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'gcr.io/$PROJECT_ID/hello-run-global']
images:
  - "gcr.io/$PROJECT_ID/hello-run-global"